spring:
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: mongo_db
      port: 27017
      host: localhost

server:
  port: 9003